language: node_js
node_js:
  "12"
matrix:
  include:
    - os: linux
    - os: osx
    - os: windows
  allow_failures:
    - os: windows
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run dist